# Generated by Django 3.0 on 2019-12-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название планеты')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=15, unique=True, verbose_name='Уникальный код')),
                ('text', models.TextField(max_length=500, verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя ситха')),
                ('planet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruting.Planet', verbose_name='Планета преподования')),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя рекрута')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='Почтовый адрес')),
                ('shadow', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Является рукой тени?')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruting.Sith')),
                ('planet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruting.Planet', verbose_name='Планета обитания')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Ответ на вопрос')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruting.Question', verbose_name='Тест')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruting.Recruit', verbose_name='Рекрут')),
            ],
        ),
    ]
