# Generated by Django 3.0 on 2019-12-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почтовый адрес'),
        ),
    ]
