# Generated by Django 3.0 on 2019-12-05 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruting', '0002_auto_20191205_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruit', to='recruting.Sith'),
        ),
    ]
